name: test
description: 意見填寫單
title: "[建議 / BUG]: "
labels: ["suggestions", "bug"]
assignees:
  - charliemoomoo
  - AWeirdScratcher
body:
  - type: markdown
    attributes:
      value: |
       感謝您願意撥空填寫此表單，請據實填寫，以免使我們判斷錯誤！
 
 - type: input
    id: name
    attributes:
      label: 我們該如何稱呼您？
      description: 可以是匿名，或是您 GitHub 帳戶的名稱！
      placeholder: 例如： 王阿貴
    validations:
      required: false

  - type: textarea
    id: sug
    attributes:
      label: 您的建議或BUG...
      description: 將它們提出來，交給我們討論
      placeholder: 我認為…
      value: "我認為"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: 出現 BUG 的版本
      description: 請選擇
      options:
        - 1.0 PRE

  - type: textarea
    id: bug
    attributes:
      label: 主控台
      description: 請複製貼上程式在主控台輸出的紀錄 (log)
      render: shell


  - type: checkboxes
    id: terms
    attributes:
      label: 請確認您已經完成下列事項：
      description: 請勾選
      options:
        - label: 我同意牛牛的TOS
          required: true
        - label: 我已經確認過沒有任何錯誤回報是跟此相同的
          required: true
        - label: 牛牛很可愛
          required: true
